"""need repoName and owner 

Revision ID: 26c6df937faf
Revises: b7c8d9e0f1a2
Create Date: 2026-05-26 14:56:11.395095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c6df937faf'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'code_chunks', 'repositories', ['repoId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'repositories', ['repoId'], ['id'])
    op.add_column('repositories', sa.Column('RepoOwner', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('RepoName', sa.String(), nullable=False))
    op.create_foreign_key(None, 'webhook_events', 'repositories', ['repoId'], ['id'])
    op.create_foreign_key(None, 'worker_tasks', 'repositories', ['repoId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_tasks', type_='foreignkey')
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_column('repositories', 'RepoName')
    op.drop_column('repositories', 'RepoOwner')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'code_chunks', type_='foreignkey')
    # ### end Alembic commands ###
