"""changed the schema 

Revision ID: 32f245b53d1b
Revises: 94e49cab512f
Create Date: 2026-05-12 01:07:30.845655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f245b53d1b'
down_revision: Union[str, Sequence[str], None] = '94e49cab512f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('repoId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repoId'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repoId', sa.String(), nullable=False),
    sa.Column('taskType', sa.Enum('FULL_PIPELINE', 'FETCH_TREE', 'FETCH_CONTENT', 'CHUNK', 'EMBED', name='task_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'RETRYING', 'SUCCESS', 'FAILED', name='task_status_enum'), nullable=False),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('maxAttempts', sa.Integer(), nullable=False),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.Column('errorType', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repoId'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worker_tasks_repoId', 'worker_tasks', ['repoId'], unique=False)
    op.create_index('ix_worker_tasks_status', 'worker_tasks', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversationId', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sourcePaths', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversationId', 'messages', ['conversationId'], unique=False)
    op.add_column('repositories', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('repositories', sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('repositories', 'license')
    op.drop_column('repositories', 'isArchived')
    op.drop_column('repositories', 'repoUpdatedAt')
    op.drop_column('repositories', 'stars')
    op.drop_column('repositories', 'repoCreatedAt')
    op.drop_column('repositories', 'sizeKb')
    op.add_column('webhook_events', sa.Column('eventType', sa.String(), nullable=False))
    op.add_column('webhook_events', sa.Column('repoId', sa.String(), nullable=True))
    op.add_column('webhook_events', sa.Column('status', sa.String(), nullable=False))
    op.add_column('webhook_events', sa.Column('processedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhook_events', sa.Column('errorMessage', sa.Text(), nullable=True))
    op.add_column('webhook_events', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'webhook_events', 'repositories', ['repoId'], ['id'])
    op.drop_column('webhook_events', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_column('webhook_events', 'createdAt')
    op.drop_column('webhook_events', 'errorMessage')
    op.drop_column('webhook_events', 'processedAt')
    op.drop_column('webhook_events', 'status')
    op.drop_column('webhook_events', 'repoId')
    op.drop_column('webhook_events', 'eventType')
    op.add_column('repositories', sa.Column('sizeKb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('repoCreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('repoUpdatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('isArchived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('repositories', sa.Column('license', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('repositories', 'updatedAt')
    op.drop_column('repositories', 'createdAt')
    op.drop_index('ix_messages_conversationId', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_worker_tasks_status', table_name='worker_tasks')
    op.drop_index('ix_worker_tasks_repoId', table_name='worker_tasks')
    op.drop_table('worker_tasks')
    op.drop_table('conversations')
    # ### end Alembic commands ###
