"""user id changed and webhook_events

Revision ID: 7044eb9dfabf
Revises: d4ac55cebbe6
Create Date: 2026-04-13 21:00:36.455785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7044eb9dfabf'
down_revision: Union[str, Sequence[str], None] = 'd4ac55cebbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id')
    )
    op.drop_table('webhookevents')
    op.add_column('users', sa.Column('clerk_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['clerk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'clerk_id')
    op.create_table('webhookevents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clerkId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('webhookevents_pkey')),
    sa.UniqueConstraint('clerkId', name=op.f('webhookevents_clerkId_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
