"""new changes 

Revision ID: 72dca4622b17
Revises: 
Create Date: 2026-04-23 19:13:03.345770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dca4622b17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_clerk_id_key'), 'users', type_='unique')
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_clerk_id_key'), 'users', ['clerk_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
