"""added clone enum 2  

Revision ID: 83ac16543f48
Revises: f6a4362e3193
Create Date: 2026-05-17 21:41:16.268105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ac16543f48'
down_revision: Union[str, Sequence[str], None] = 'f6a4362e3193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'repositories', ['repoId'], ['id'])
    op.create_foreign_key(None, 'webhook_events', 'repositories', ['repoId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
