"""changed enum values to id type  

Revision ID: 88e9023aa80d
Revises: 83ac16543f48
Create Date: 2026-05-19 17:29:27.975567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88e9023aa80d'
down_revision: Union[str, Sequence[str], None] = '83ac16543f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repo_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('messages', sa.Column('roleId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'message_roles', ['roleId'], ['id'])
    op.drop_column('messages', 'role')
    op.add_column('repositories', sa.Column('statusId', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.create_index('ix_repositories_status', 'repositories', ['statusId'], unique=False)
    op.create_foreign_key(None, 'repositories', 'repo_statuses', ['statusId'], ['id'])
    op.drop_column('repositories', 'status')
    op.add_column('worker_tasks', sa.Column('taskTypeId', sa.Integer(), nullable=False))
    op.add_column('worker_tasks', sa.Column('statusId', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_worker_tasks_status'), table_name='worker_tasks')
    op.create_index('ix_worker_tasks_status', 'worker_tasks', ['statusId'], unique=False)
    op.create_foreign_key(None, 'worker_tasks', 'task_statuses', ['statusId'], ['id'])
    op.create_foreign_key(None, 'worker_tasks', 'task_types', ['taskTypeId'], ['id'])
    op.drop_column('worker_tasks', 'taskType')
    op.drop_column('worker_tasks', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_tasks', sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'RETRYING', 'SUCCESS', 'FAILED', name='task_status_enum'), autoincrement=False, nullable=False))
    op.add_column('worker_tasks', sa.Column('taskType', postgresql.ENUM('FULL_PIPELINE', 'FETCH_TREE', 'FETCH_CONTENT', 'CHUNK', 'EMBED', name='task_type_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'worker_tasks', type_='foreignkey')
    op.drop_constraint(None, 'worker_tasks', type_='foreignkey')
    op.drop_index('ix_worker_tasks_status', table_name='worker_tasks')
    op.create_index(op.f('ix_worker_tasks_status'), 'worker_tasks', ['status'], unique=False)
    op.drop_column('worker_tasks', 'statusId')
    op.drop_column('worker_tasks', 'taskTypeId')
    op.add_column('repositories', sa.Column('status', postgresql.ENUM('PENDING', 'INDEXING', 'INDEXED', 'FAILED', 'OUTDATED', name='repo_status_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_index('ix_repositories_status', table_name='repositories')
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.drop_column('repositories', 'statusId')
    op.add_column('messages', sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', name='message_role_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'roleId')
    op.drop_table('task_types')
    op.drop_table('task_statuses')
    op.drop_table('repo_statuses')
    op.drop_table('message_roles')
    # ### end Alembic commands ###
