"""new parsing status 

Revision ID: 8c09c4609e7c
Revises: 88e9023aa80d
Create Date: 2026-05-20 21:33:21.730983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c09c4609e7c'
down_revision: Union[str, Sequence[str], None] = '88e9023aa80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_connections_repoId'), table_name='code_connections')
    op.drop_index(op.f('ix_code_connections_sourceChunkId'), table_name='code_connections')
    op.drop_index(op.f('ix_code_connections_targetChunkId'), table_name='code_connections')
    op.drop_table('code_connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_connections',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('repoId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sourceChunkId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('targetSymbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('targetChunkId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('connectionType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repoId'], ['repositories.id'], name=op.f('code_connections_repoId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sourceChunkId'], ['code_chunks.id'], name=op.f('code_connections_sourceChunkId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['targetChunkId'], ['code_chunks.id'], name=op.f('code_connections_targetChunkId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('code_connections_pkey'))
    )
    op.create_index(op.f('ix_code_connections_targetChunkId'), 'code_connections', ['targetChunkId'], unique=False)
    op.create_index(op.f('ix_code_connections_sourceChunkId'), 'code_connections', ['sourceChunkId'], unique=False)
    op.create_index(op.f('ix_code_connections_repoId'), 'code_connections', ['repoId'], unique=False)
    # ### end Alembic commands ###
