"""added clone enum  

Revision ID: f6a4362e3193
Revises: db63a5674a8e
Create Date: 2026-05-17 21:31:45.795485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a4362e3193'
down_revision: Union[str, Sequence[str], None] = 'db63a5674a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'repositories', ['repoId'], ['id'])
    op.create_foreign_key(None, 'webhook_events', 'repositories', ['repoId'], ['id'])
    op.create_foreign_key(None, 'worker_tasks', 'repositories', ['repoId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_tasks', type_='foreignkey')
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
