"""updated reposotry table 

Revision ID: fe0313a069ec
Revises: 8c09c4609e7c
Create Date: 2026-05-20 22:23:37.516746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0313a069ec'
down_revision: Union[str, Sequence[str], None] = '8c09c4609e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'repoName')
    op.drop_column('repositories', 'repoOwner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('repoOwner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('repoName', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
